### ISSUE TITLE
False claim that install is from an "unofficial" source.

### ISSUE THREAD

**Issue by Mightyena23** [theomenden/TheOmenDen.ConfigurableBossBars#35]
I logged into a fresh world using this mod among others in a personal save and I got a message in chat warning me about the file name being changed and that is likely due to installing it from an "unofficial" source. It went on to say how those sites harm the creator. 
I installed it using the Curse Forge launcher, however, so I don't see how that's the case; which is why I believe it is a false popup. 

Unfortunately, I didn't get a screenshot of the message that appeared and I have been unable to get it to pop up again, but I believe that it would have been after I updated my mods and launched my game (through the Curse Forge launcher). 

I installed it through [Modrinth](https://modrinth.com/mod/configurable-boss-bars) manually just in case but I wanted to bring this to your attention. 

Thanks for reading!

**Comment by AluTheCrow** [comment]
Ah.
Yeah thanks for bringing this to my attention - must've missed something in one of the build steps.

I'll work on fixing it for the next release!

**Comment by Mightyena23** [comment]
No problem! 
Good luck haha, Shall I close this then?

**Comment by AluTheCrow** [comment]
No need, it'll auto-close when I mention it in my next commit/release.

**Comment by Mightyena23** [comment]
Oop. Alright then! 
New to this lol 

Anyway thanks for the quick reponse!

**Comment by Mightyena23** [comment]
So I did get it to pop up again (unintentionally) 
but this is the message in case it helps.

![Screenshot (78)](https://github.com/user-attachments/assets/b3e40715-1aea-4376-8028-978abe997001)

**Comment by AluTheCrow** [comment]
Closed as a result of commit https://github.com/theomenden/TheOmenDen.ConfigurableBossBars/commit/f85269b76ddf1480ea80a1cbc499667f42a32915
